Quiz_Application/Quiz_Application/Models/QuestionLevel.cs
using System.ComponentModel.DataAnnotations;

namespace Quiz_Application.Models
{
    public class QuestionLevel
    {
        public int? QuestionLevelID { get; set; }

        [Required(ErrorMessage = "Question level is required")]
        [StringLength(100, ErrorMessage = "Question level cannot exceed 100 characters")]
        public string QuestionLevelName { get; set; } // Renamed for clarity

        [Required(ErrorMessage = "User ID is required")]
        public int UserID { get; set; } // Foreign Key to MST_User
 
    }


    public class Level
    {
        public int? QuestionLevelID { get; set; }

        
        public string QuestionLevelName { get; set; }
    }

    public class AppUser
    {
        public int UserID { get; set; }
        public string Username { get; set; }
    }

}

Quiz_Application/Quiz_Application/Controllers/MST_QuestionLevelController.cs
using System.Data.SqlClient;
using System.Data;
using Microsoft.AspNetCore.Mvc;
using Quiz_Application.Models;
using OfficeOpenXml;
using System.Reflection.Emit;

namespace Quiz_Application.Controllers
{
    public class MST_QuestionLevelController : Controller
    {
        private IConfiguration configuration;

        public MST_QuestionLevelController(IConfiguration _configuration)
        {
            configuration = _configuration;
        }
        public IActionResult QuestionLevelForm(int QuestionLevelID)
        {

            if (QuestionLevelID == 0)
            {
                TempData["PageTitle"] = "Add QuestionLevel";
            }
            else
            {
                TempData["PageTitle"] = "Edit QuestionLevel";
            }

            //------------Question Level Drop Down Model
            string questionLevelConnectionString = this.configuration.GetConnectionString("ConnectionString");




            ViewBag.QuestionLevelID = QuestionLevelID;
            SqlConnection QuestionSqlConnection = new SqlConnection(questionLevelConnectionString);
            QuestionSqlConnection.Open();
            SqlCommand questionSqlCommand = QuestionSqlConnection.CreateCommand();
            questionSqlCommand.CommandType = CommandType.StoredProcedure;
            questionSqlCommand.CommandText = "Sp_MST_QuestionLevel_SelectByID";
            questionSqlCommand.Parameters.AddWithValue("@QuestionLevelID", QuestionLevelID);
            SqlDataReader questionlevelReader = questionSqlCommand.ExecuteReader();
            DataTable questionlevelTable = new DataTable();
            questionlevelTable.Load(questionlevelReader);
            QuestionLevel questionLevelModel = new QuestionLevel();

            foreach (DataRow dataRow in questionlevelTable.Rows)
            {
                questionLevelModel.QuestionLevelID = Convert.ToInt32(@dataRow["QuestionLevelID"]);
                questionLevelModel.QuestionLevelName = @dataRow["QuestionLevel"].ToString();
                questionLevelModel.UserID = Convert.ToInt32(@dataRow["UserID"]);
            }
            Console.WriteLine(questionLevelModel);
            return View("QuestionLevelForm", questionLevelModel);
        }
        public IActionResult QuestionLevelList()
        {
            string connectionString = this.configuration.GetConnectionString("ConnectionString");
            SqlConnection connection = new SqlConnection(connectionString);
            connection.Open();
            SqlCommand command = connection.CreateCommand();
            command.CommandType = CommandType.StoredProcedure;
            command.CommandText = "Sp_MST_QuestionLevel_SelectAll";
            SqlDataReader reader = command.ExecuteReader();
            DataTable table = new DataTable();
            table.Load(reader);
            return View(table);
        }
        public IActionResult QuestionLevelDelete(int QuestionLevelID)
        {
            try
            {
                string connectionString = configuration.GetConnectionString("ConnectionString");
                using (SqlConnection connection = new SqlConnection(connectionString))
                {
                    connection.Open();
                    SqlCommand command = connection.CreateCommand();
                    command.CommandType = CommandType.StoredProcedure;
                    command.CommandText = "Sp_MST_QuestionLevel_DeleteByID";
                    command.Parameters.Add("@QuestionLevelID", SqlDbType.Int).Value = QuestionLevelID;


                    command.ExecuteNonQuery();
                }

                TempData["SuccessMessage"] = "QuestionLevel deleted successfully.";
                return RedirectToAction("QuestionLevelList");
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = "An error occurred while deleting the QuestionLevel: " + ex.Message;
                return RedirectToAction("QuestionLevelList");
            }
        }
        public IActionResult QuestionLevelAddEdit(int? QuestionLevelID)
        {
            QuestionLevel model = new QuestionLevel();

            if (QuestionLevelID != null && QuestionLevelID > 0)
            {
                string connectionString = configuration.GetConnectionString("ConnectionString");
                using (SqlConnection connection = new SqlConnection(connectionString))
                {
                    connection.Open();
                    SqlCommand command = new SqlCommand("Sp_MST_QuestionLevel_SelectByID", connection);
                    command.CommandType = CommandType.StoredProcedure;
                    command.Parameters.Add("@QuestionLevelID", SqlDbType.Int).Value = QuestionLevelID;

                    SqlDataReader reader = command.ExecuteReader();
                    if (reader.Read())
                    {
                        model.QuestionLevelID = Convert.ToInt32(reader["QuestionLevelID"]);
                        model.QuestionLevelName = reader["QuestionLevel"].ToString();
                        model.UserID = Convert.ToInt32(reader["UserID"]);
                       
                    }
                }
            }
            return View("QuestionLevelForm", model);
        }

        // POST: Save Question (Insert/Update)
        [HttpPost]
        public IActionResult QuestionLevelSave(QuestionLevel model)
        {
            if (ModelState.IsValid)
            {
                string connectionString = configuration.GetConnectionString("ConnectionString");
                using (SqlConnection connection = new SqlConnection(connectionString))
                {
                    connection.Open();
                    SqlCommand command = new SqlCommand
                    {
                        Connection = connection,
                        CommandType = CommandType.StoredProcedure
                    };

                    if (model.QuestionLevelID == null || model.QuestionLevelID == 0) // Insert
                    {
                        command.CommandText = "Sp_MST_QuestionLevel_Insert";
                    }
                    else // Update
                    {
                        command.CommandText = "Sp_MST_QuestionLevel_Update";
                        command.Parameters.Add("@QuestionLevelID", SqlDbType.Int).Value = model.QuestionLevelID;
                    }

                    // Common parameters
                    command.Parameters.Add("@QuestionLevel", SqlDbType.NVarChar).Value = model.QuestionLevelName;
                    command.Parameters.Add("@UserID", SqlDbType.Int).Value = model.UserID;

                    command.ExecuteNonQuery();
                }
                return RedirectToAction("QuestionLevelList");
            }

            return View("QuestionLevelForm", model);
        }
        public IActionResult ExportToExcel()
        {
            string connectionString = configuration.GetConnectionString("ConnectionString");
            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                connection.Open();
                SqlCommand command = new SqlCommand("Sp_MST_QuestionLevel_SelectAll", connection) // Updated stored procedure
                {
                    CommandType = CommandType.StoredProcedure
                };

                SqlDataReader reader = command.ExecuteReader();
                DataTable data = new DataTable();
                data.Load(reader);

                using (var package = new ExcelPackage())
                {
                    var worksheet = package.Workbook.Worksheets.Add("QuestionLevels");

                    // Add headers (without UserID)
                    worksheet.Cells[1, 1].Value = "QuestionLevelID";
                    worksheet.Cells[1, 2].Value = "QuestionLevel";
                    worksheet.Cells[1, 3].Value = "UserName"; // Kept UserName
                    worksheet.Cells[1, 4].Value = "Created";
                    worksheet.Cells[1, 5].Value = "Modified";

                    // Add data
                    int row = 2;
                    foreach (DataRow item in data.Rows)
                    {
                        worksheet.Cells[row, 1].Value = item["QuestionLevelID"];
                        worksheet.Cells[row, 2].Value = item["QuestionLevel"];
                        worksheet.Cells[row, 3].Value = item["UserName"]; // Fetching UserName
                        worksheet.Cells[row, 4].Value = Convert.ToDateTime(item["Created"]).ToString("yyyy-MM-dd HH:mm:ss"); // Formatting datetime
                        worksheet.Cells[row, 5].Value = Convert.ToDateTime(item["Modified"]).ToString("yyyy-MM-dd HH:mm:ss"); // Formatting datetime
                        row++;
                    }

                    var stream = new MemoryStream();
                    package.SaveAs(stream);
                    stream.Position = 0;

                    string excelName = $"QuestionLevels-{DateTime.Now:yyyyMMddHHmmss}.xlsx";
                    return File(stream, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", excelName);
                }
            }
        }

        public IActionResult QuestionLevelSearch(int? questionLevelID, string username)
        {
            string connectionString = configuration.GetConnectionString("ConnectionString");
            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                connection.Open();
                SqlCommand command = new SqlCommand("Sp_MST_QuestionLevel_Search", connection)
                {
                    CommandType = CommandType.StoredProcedure
                };

                command.Parameters.AddWithValue("@QuestionLevelID", (object)questionLevelID ?? DBNull.Value);
                command.Parameters.AddWithValue("@Username", (object)username ?? DBNull.Value);

Quiz_Application/Quiz_Application/Views/MST_QuestionLevel/QuestionLevelForm.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model Quiz_Application.Models.QuestionLevel

<main id="main" class="main">

    <div class="pagetitle">
        <h1>Add/Edit QuestionLevel</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a asp-Controller="Home" asp-action="Index">Home</a></li>
                <li class="breadcrumb-item">Forms</li>
                <li class="breadcrumb-item active">Layouts</li>
            </ol>
        </nav>
    </div><!-- End Page Title -->
    <section class="section">
        <div class="row">
            <div class="col-lg-100">

                <div class="card">
                    <div class="card-body">

                        <!-- Horizontal Form -->
                        <body>
                            <div class="container mt-5">
                                <h2 class="mb-4">Add/Edit QuestionLevel</h2>

                                <!-- Form for entering question level data -->
                                <form asp-action="QuestionLevelSave" asp-controller="MST_QuestionLevel" method="POST">
                                    <input type="hidden" asp-for="QuestionLevelID" />

                                    <div class="mb-3">
                                        <label for="questionLevel" class="form-label"> <span style="color: red;">*</span> Question Level</label>
                                        <input asp-for="QuestionLevelName" type="text" class="form-control" placeholder="Enter a Question Level (e.g.,Easy,Midium,Hard)">
                                        <span asp-validation-for="QuestionLevelName" class="form-text  text-danger"></span>
                                    </div>
                                    <div class="mb-3">
                                        <label for="userName" class="form-label"> <span style="color: red;">*</span> User Name</label>
                                        <input asp-for="UserID" type="text" class="form-control">
                                        <span asp-validation-for="UserID" class="form-text  text-danger"></span>
                                    </div>
                                    @* <div class="mb-3"> *@
                                    @*     <label for="created" class="form-label">Created</label> *@
                                    @*     <input type="datetime-local" class="form-control" id="created" name="created" required> *@
                                    @* </div> *@
                                    @* <div class="mb-3"> *@
                                    @*     <label for="modified" class="form-label">Modified</label> *@
                                    @*     <input type="datetime-local" class="form-control" id="modified" name="modified" required> *@
                                    @* </div> *@

                                    <!-- Submit Button -->
                                    <button type="submit" class="btn btn-success">Submit</button>
                                    <a class="btn btn-danger" asp-controller="MST_QuestionLevel" asp-action="QuestionLevelList">Cancle</a>

                                </form>
                            </div>

                            
                        </body>
                        <!-- End Horizontal Form -->

                    </div>
                </div>
                </div></div></section></main>

@section Scripts {
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.3/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.12/jquery.validate.unobtrusive.min.js"></script>

}

Quiz_Application/Quiz_Application/Views/MST_QuestionLevel/QuestionLevelList.cshtml
@model DataTable
@using System.Data
<main id="main" class="main">

    <div class="pagetitle">
        <h1>QuestionLevel List</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a asp-Controller="Home" asp-action="Index">Home</a></li>
                <li class="breadcrumb-item">Tables</li>
                <li class="breadcrumb-item active">Data</li>
            </ol>
        </nav>
    </div><!-- End Page Title -->
@*     <section class="section"> *@
@*         <div class="row"> *@
@*             <div class="col-lg-100"> *@

@*                 <div class="card"> *@
@*                     <div class="card-body"> *@

@*                             <h5 class="card-title">Search Question Level</h5> *@

@*                                <form class="row g-3" method="get" asp-action="QuestionLevelSearch"> *@
@*                                     <div class="col-md-4"> *@
@*                                         <label for="questionLevelID" class="form-label">Question Level</label> *@
@*                                         <select name="questionLevelID" class="form-control"> *@
@*                                             <option value="">Select Level</option> *@
@*                                             @if (ViewBag.Levels != null) *@
@*                                             { *@
@*                                                 foreach (var v in ViewBag.Levels) *@
@*                                                 { *@
@*                                                     <option value="@v.QuestionLevelID">@v.QuestionLevelName</option> *@
@*                                                 } *@
@*                                             } *@
@*                                         </select> *@
@*                                     </div> *@

@*                                     <div class="col-md-4"> *@
@*                                         <label for="username" class="form-label">Username</label> *@
@*                                        <select name="username" class="form-control"> *@
@*                                     <option value="">Select User</option> *@
@*                                     @if (ViewBag.Usernames != null) *@
@*                                     { *@
@*                                         foreach (var user in ViewBag.Usernames) *@
@*                                         { *@
@*                                             <option value="@user.UserID">@user.Username</option> *@
@*                                         } *@
@*                                     } *@
@*                                 </select> *@
@*                                     </div> *@

@*                                     <div class="text-start"> *@
@*                                         <button type="submit" class="btn btn-success">Search</button> *@
@*                                         <button type="reset" class="btn btn-danger">Reset</button> *@
@*                                     </div> *@
@*                                 </form> *@
@*                    </div> *@
@*                 </div> *@
@*             </div> *@
@*          </div> *@
@* </section> *@

    <br> <div class="text-danger">
                            @{
        if (@TempData["SuccessMessage"] != null)
        {
            <p>@TempData["SuccessMessage"]</P>
    }
     if (@TempData["ErrorMessage"] != null)
        {
            <p>@TempData["ErrorMessage"]</P>
    }
    }
    </div>
    <section class="section">
        <div class="row">
            <div class="col-lg-12">

                <div class="card">
                    <div class="card-body">
                       

                        @* <h2 class="p-3">Question Level List</h2> *@
                        @* <div class="d-flex p-3 justify-content-end"> *@
                        @*     <a asp-action="" asp-controller="" class="btn btn-danger"> *@
                        @*         <i class="bi"></i> Delete Selected *@
                        @*     </a> *@
                        @*     <a asp-action="QuestionLevelForm" asp-controller="MST_QuestionLevel" class="btn btn-primary"> *@
                        @*         <i class="bi bi-plus"></i> Add Question Level *@
                        @*     </a> *@
                        @* </div> *@


                         @*<span class="text-danger">@TempData["ErrorMessage"]</span>*@

                          <div class="m-3">
                                <a asp-controller="MST_QuestionLevel" asp-action="ExportToExcel" class="btn btn-primary float-end ms-2 mb-4 mt-1">
                                    <i class="fa fa-file-excel"></i> Download Excel
                                </a>
                            </div>
                        <a class="btn btn-success float-end mb-2 mt-1" asp-area="" asp-controller="MST_QuestionLevel" asp-action="QuestionLevelForm">Add Question Level</a>

                        <!-- Table with stripped rows -->
                        <table class="table datatable">
                            <h2 class="mt-3">Question Level list</h2>

                                        <thead>
                                            <tr>
                                                <th>Question Level ID</th>
                                                <th>Question Level</th>
                                                <th>User Name</th>
                                                <th>Created</th>
                                                <th>Modified</th>
                                                 <th>Action</th>

                                            </tr>
                                        </thead>
                                        <tbody>
                                @foreach (DataRow dataRow in Model.Rows)
                                {
                                    <tr>
                                        <td>@dataRow["QuestionLevelID"]</td>
                                        <td>@dataRow["QuestionLevel"]</td>
                                        <td>@dataRow["UserName"]</td>
                                        <td>@dataRow["Created"]</td>
                                        <td>@dataRow["Modified"]</td>
                                        <td>
                                            <a asp-controller="MST_QuestionLevel" asp-action="QuestionLevelForm"  asp-route-QuestionLevelID="@dataRow["QuestionLevelID"]" class="btn btn-primary" onclick="return confirm('Are you sure you want to Edit this QuestionLevel?')">
                                                <i class="bi bi-pencil-fill"></i>Edit

                                            </a>
                                            <a asp-controller="MST_QuestionLevel" asp-action="QuestionLevelDelete" asp-route-QuestionLevelID="@dataRow["QuestionLevelID"]" class="btn btn-danger btn-xs" onclick="return confirm('Are you sure you want to delete this QuestionLevel?')">
                                                <i class="bi bi-trash">Delete</i>
                                            </a>

                                        </td>
                                    </tr>

                                }
                               </tbody>
                               

                                
                           
                           </table>
                        <!-- End Table with stripped rows -->

                    </div>
                </div>

            </div>
        </div>
    </section>
  