Quiz_Application/Quiz_Application/Models/Question.cs
using System.ComponentModel.DataAnnotations;

namespace Quiz_Application.Models
{
    public class Question
    {
        public int? QuestionID { get; set; }
        [Required(ErrorMessage = "Question text is required")]
        public string QuestionText { get; set; }

        [Required(ErrorMessage = "Question level is required")]
        public int QuestionLevelID { get; set; } // Foreign Key to MST_QuestionLevel

        [Required(ErrorMessage = "Option A is required")]
        [StringLength(100, ErrorMessage = "Option A cannot exceed 100 characters")]
        public string OptionA { get; set; }

        [Required(ErrorMessage = "Option B is required")]
        [StringLength(100, ErrorMessage = "Option B cannot exceed 100 characters")]
        public string OptionB { get; set; }

        [Required(ErrorMessage = "Option C is required")]
        [StringLength(100, ErrorMessage = "Option C cannot exceed 100 characters")]
        public string OptionC { get; set; }

        [Required(ErrorMessage = "Option D is required")]
        [StringLength(100, ErrorMessage = "Option D cannot exceed 100 characters")]
        public string OptionD { get; set; }

        [Required(ErrorMessage = "Correct option is required")]
        //[RegularExpression("^(A|B|C|D)$", ErrorMessage = "Correct option must be A, B, C, or D")]
        public string CorrectOption { get; set; }

        [Required(ErrorMessage = "Question marks are required")]
        [Range(1, int.MaxValue, ErrorMessage = "Marks must be at least 1")]
        public int QuestionMarks { get; set; }
        public bool IsActive { get; set; } = true;


        [Required(ErrorMessage = "User ID is required")]
        public int UserID { get; set; } // Foreign Key to MST_User

       
    }
    public class QuestionLevelDropdown
    {
        public int QuestionLevelID { get; set; }
        public string QuestionLevel { get; set; }

        // Parameterized constructor (optional)
       
    }

}

Quiz_Application/Quiz_Application/Controllers/MST_QuestionController.cs
using System.Data.SqlClient;
using System.Data;
using Microsoft.AspNetCore.Mvc;
using Quiz_Application.Models;
using Microsoft.Extensions.Configuration;
using OfficeOpenXml;

namespace Quiz_Application.Controllers
{
    public class MST_QuestionController : Controller
    {
        private IConfiguration configuration;

        public MST_QuestionController(IConfiguration _configuration)
        {
            configuration = _configuration;
        }
        //[Route("AddEditQuestion")]
        //public IActionResult QuestionForm()
        //{
        //    return View();
        //}
        public IActionResult QuestionList()
        {
            QuestionLevelDropdown();
            string connectionString = this.configuration.GetConnectionString("ConnectionString");
            SqlConnection connection = new SqlConnection(connectionString);
            connection.Open();
            SqlCommand command = connection.CreateCommand();
            command.CommandType = CommandType.StoredProcedure;
            command.CommandText = "Sp_MST_Question_SelectAllQuestions";
            SqlDataReader reader = command.ExecuteReader();
            DataTable table = new DataTable();
            table.Load(reader);
            return View(table);
        }
        public IActionResult QuestionDelete(int QuestionID)
        {
            try
            {
                string connectionString = configuration.GetConnectionString("ConnectionString");
                using (SqlConnection connection = new SqlConnection(connectionString))
                {
                    connection.Open();
                    SqlCommand command = connection.CreateCommand();
                    command.CommandType = CommandType.StoredProcedure;
                    command.CommandText = "Sp_MST_Question_DeleteQuestionByID";
                    command.Parameters.Add("@QuestionID", SqlDbType.Int).Value = QuestionID;


                    command.ExecuteNonQuery();
                }

                TempData["SuccessMessage"] = "Question deleted successfully.";
                return RedirectToAction("QuestionList");
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = "An error occurred while deleting the Qustion: " + ex.Message;
                return RedirectToAction("QuestionList");
            }
        }


        //public IActionResult questionAddEdit(Question model)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        string connectionString = configuration.GetConnectionString("ConnectionString");
        //        SqlConnection connection = new SqlConnection(connectionString);
        //        connection.Open();
        //        SqlCommand command = connection.CreateCommand();
        //        command.CommandType = CommandType.StoredProcedure;

        //        if (model.QuestionID == 0)
        //        {
        //            command.CommandText = "Sp_MST_Question_InsertNewQuestion";
        //        }
        //        else
        //        {
        //            command.CommandText = "Sp_MST_Question_UpdateQuestion";
        //            command.Parameters.Add("@QuestionID", SqlDbType.Int).Value = model.QuestionID;
        //        }
        //        command.Parameters.Add("@QuestionText", SqlDbType.VarChar).Value = model.QuestionText;
        //        command.Parameters.Add("@QuestionLevelID", SqlDbType.VarChar).Value = model.QuestionLevelID;
        //        command.Parameters.Add("@OptionA", SqlDbType.VarChar).Value = model.@OptionA;
        //        command.Parameters.Add("@OptionB", SqlDbType.VarChar).Value = model.@OptionB;
        //        command.Parameters.Add("@OptionC", SqlDbType.VarChar).Value = model.@OptionC;
        //        command.Parameters.Add("@OptionD", SqlDbType.VarChar).Value = model.@OptionD;

        //        command.Parameters.Add("@CorrectOption", SqlDbType.VarChar).Value = model.CorrectOption;
              

        //        //command.Parameters.Add("@UserID", SqlDbType.Int).Value = CommonVariable.UserID();
        //        command.ExecuteNonQuery();
        //        return RedirectToAction("QuestionList");
        //    }

        //    return View("QuestionForm", model);
        //}


        public IActionResult QuestionForm(int QuestionID)
        {
            if (QuestionID == 0)
            {
                TempData["PageTitle"] = "Add Question";
            }
            else
            {
                TempData["PageTitle"] = "Edit Question";
            }

            //------------Question Level Drop Down Model
            string questionLevelConnectionString = this.configuration.GetConnectionString("ConnectionString");

            FillQuestionLevelDropDown();


            ViewBag.QuestionID = QuestionID;
            SqlConnection QuestionSqlConnection = new SqlConnection(questionLevelConnectionString);
            QuestionSqlConnection.Open();
            SqlCommand questionSqlCommand = QuestionSqlConnection.CreateCommand();
            questionSqlCommand.CommandType = CommandType.StoredProcedure;
            questionSqlCommand.CommandText = "Sp_MST_Question_SelectQuestionByID";
            questionSqlCommand.Parameters.AddWithValue("@QuestionID", QuestionID);
            SqlDataReader questionReader = questionSqlCommand.ExecuteReader();
            DataTable questionTable = new DataTable();
            questionTable.Load(questionReader);
            Question questionModel = new Question();

            foreach (DataRow dataRow in questionTable.Rows)
            {
                questionModel.QuestionID = Convert.ToInt32(@dataRow["QuestionID"]);
                questionModel.QuestionText = @dataRow["QuestionText"].ToString();
                questionModel.QuestionLevelID = Convert.ToInt32(@dataRow["QuestionLevelID"]);
                questionModel.OptionA = @dataRow["OptionA"].ToString();
                questionModel.OptionB = @dataRow["OptionB"].ToString();
                questionModel.OptionC = @dataRow["OptionC"].ToString();
                questionModel.OptionD = @dataRow["OptionD"].ToString();
                questionModel.CorrectOption = @dataRow["CorrectOption"].ToString();
                questionModel.QuestionMarks = Convert.ToInt32(@dataRow["QuestionMarks"]);
                questionModel.UserID = Convert.ToInt32(@dataRow["UserID"]);
            }
            Console.WriteLine(questionModel);
            return View("QuestionForm", questionModel);
        }

        private void FillQuestionLevelDropDown()
        {
            string questionLevelConnectionString = this.configuration.GetConnectionString("ConnectionString");
            SqlConnection questionLevelSqlConnection = new SqlConnection(questionLevelConnectionString);
            questionLevelSqlConnection.Open();
            SqlCommand questionLevelSqlCommand = questionLevelSqlConnection.CreateCommand();
            questionLevelSqlCommand.CommandType = CommandType.StoredProcedure;
            questionLevelSqlCommand.CommandText = "Sp_MST_QuestionLevel_SelectAll";
            SqlDataReader questionLevelReader = questionLevelSqlCommand.ExecuteReader();
            DataTable questionLevelDataTable = new DataTable();
            questionLevelDataTable.Load(questionLevelReader);
            List<QuestionLevelDropdown> questionLevelList = new List<QuestionLevelDropdown>();
            foreach (DataRow data in questionLevelDataTable.Rows)
            {
                QuestionLevelDropdown questionLevelDropDownModel = new QuestionLevelDropdown();
                questionLevelDropDownModel.QuestionLevelID = Convert.ToInt32(data["QuestionLevelID"]);
                questionLevelDropDownModel.QuestionLevel = data["QuestionLevel"].ToString();
                questionLevelList.Add(questionLevelDropDownModel);
            }
            ViewBag.QuestionLevelList = questionLevelList;
        }

        public IActionResult QuestionAddEdit(int? QuestionID)
        {
            Question model = new Question();

            if (QuestionID != null && QuestionID > 0)
            {
                string connectionString = configuration.GetConnectionString("ConnectionString");
                using (SqlConnection connection = new SqlConnection(connectionString))
                {
                    connection.Open();
                    SqlCommand command = new SqlCommand("Sp_MST_Question_SelectQuestionByID", connection);
                    command.CommandType = CommandType.StoredProcedure;
                    command.Parameters.Add("@QuestionID", SqlDbType.Int).Value = QuestionID;

                    SqlDataReader reader = command.ExecuteReader();
                    if (reader.Read())
                    {
                        model.QuestionID = Convert.ToInt32(reader["QuestionID"]);
                        model.QuestionText = reader["QuestionText"].ToString();
                        model.QuestionLevelID = Convert.ToInt32(reader["QuestionLevelID"]);
                        model.OptionA = reader["OptionA"].ToString();
                        model.OptionB = reader["OptionB"].ToString();
                        model.OptionC = reader["OptionC"].ToString();
                        model.OptionD = reader["OptionD"].ToString();
                        model.CorrectOption = reader["CorrectOption"].ToString();
                        model.QuestionMarks = Convert.ToInt32(reader["QuestionMarks"]);
                        model.IsActive = Convert.ToBoolean(reader["IsActive"]);
                        model.UserID = Convert.ToInt32(reader["UserID"]);
                    }
                }
            }
            return View("QuestionForm", model);
        }

        // POST: Save Question (Insert/Update)
        [HttpPost]
        public IActionResult QuestionSave(Question model)
        {
            if (ModelState.IsValid)
            {

Quiz_Application/Quiz_Application/Views/MST_Question/QuestionForm.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model Quiz_Application.Models.Question

<main id="main" class="main">

    <div class="pagetitle">
        <h1> Add/Edit Question</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a asp-Controller="Home" asp-action="Index">Home</a></li>
                <li class="breadcrumb-item">Forms</li>
                <li class="breadcrumb-item active">Layouts</li>
            </ol>
        </nav>
    </div><!-- End Page Title -->
    <section class="section">
        <div class="row">
            <div class="col-lg-100">

                <div class="card">
                    <div class="card-body">

                        <!-- Horizontal Form -->
                        <body>
                            <div class="container mt-5">
                                <h2 class="mb-4">Add/Edit Question</h2>
                                <form asp-action="QuestionSave" asp-controller="MST_Question" method="POST">
                                    <input type="hidden" asp-for="QuestionID" />
                                    <div class="mb-3">
                                        <label for="questiontext" class="form-label"><span style="color: red;">*</span>Question Text</label>
                                        <textarea asp-for="QuestionText" class="form-control" placeholder="Enter Question"></textarea>
                                        <span asp-validation-for="QuestionText" class="form-text text-danger"></span>
                                    </div>

                                    <div class="mb-3">
                                        <label for="questionlevelid" class="form-label"><span style="color: red;">*</span>Question Level</label>
                                        <select class="form-select" asp-for="QuestionLevelID" asp-items="@(new SelectList(ViewBag.QuestionLevelList, "QuestionLevelID", "QuestionLevel"))">
                                            <option value="" selected>Select Question Level</option>
                                        </select>
                                        <span asp-validation-for="QuestionLevelID" class="form-text text-danger"></span>
                                    </div>

                                    <div class="mb-3">
                                        <label for="optiona" class="form-label"><span style="color: red;">*</span>Option A</label>
                                        <input asp-for="OptionA" type="text" class="form-control" placeholder="Enter Option A">
                                        <span asp-validation-for="OptionA" class="form-text text-danger"></span>
                                    </div>

                                    <div class="mb-3">
                                        <label for="optionb" class="form-label"><span style="color: red;">*</span>Option B</label>
                                        <input asp-for="OptionB" type="text" class="form-control" placeholder="Enter Option B">
                                        <span asp-validation-for="OptionB" class="form-text text-danger"></span>
                                    </div>

                                    <div class="mb-3">
                                        <label for="optionc" class="form-label"><span style="color: red;">*</span>Option C</label>
                                        <input asp-for="OptionC" type="text" class="form-control" placeholder="Enter Option C">
                                        <span asp-validation-for="OptionC" class="form-text text-danger"></span>
                                    </div>

                                    <div class="mb-3">
                                        <label for="optiond" class="form-label"><span style="color: red;">*</span>Option D</label>
                                        <input asp-for="OptionD" type="text" class="form-control" placeholder="Enter Option D">
                                        <span asp-validation-for="OptionD" class="form-text text-danger"></span>
                                    </div>

                                    <div class="mb-3">
                                        <label for="correctoption" class="form-label"><span style="color: red;">*</span>Correct Option</label>
                                        <select asp-for="CorrectOption" class="form-control">
                                            <option value="">Select Correct Option</option>
                                            <option value="A">Option A</option>
                                            <option value="B">Option B</option>
                                            <option value="C">Option C</option>
                                            <option value="D">Option D</option>
                                        </select>
                                        <span asp-validation-for="CorrectOption" class="form-text text-danger"></span>
                                    </div>

                                    <div class="mb-3">
                                        <label for="questionmarks" class="form-label"><span style="color: red;">*</span>Question Marks</label>
                                        <input asp-for="QuestionMarks" type="number" class="form-control" min="1">
                                        <span asp-validation-for="QuestionMarks" class="form-text text-danger"></span>
                                    </div>

                                    <div class="mb-3">
                                        <label for="isactive" class="form-label"><span style="color: red;">*</span>Is Active</label>
                                        <select asp-for="IsActive" class="form-control">
                                            <option value="true" selected="@(Model.IsActive ? "selected" : null)">Active</option>
                                            <option value="false" selected="@(Model.IsActive ? null : "selected")">Inactive</option>
                                        </select>
                                        <span asp-validation-for="IsActive" class="form-text text-danger"></span>
                                    </div>

                                    <div class="mb-3">
                                        <label for="userid" class="form-label"><span style="color: red;">*</span>User ID</label>
                                        <input asp-for="UserID" type="number" class="form-control" min="1">
                                        <span asp-validation-for="UserID" class="form-text text-danger"></span>
                                    </div>

                                    <button type="submit" class="btn btn-success">Submit</button>
                                    <a class="btn btn-danger" asp-controller="MST_Question" asp-action="QuestionList">Cancel</a>
                                </form>
                    </div>

                            
                        </body>
                        <!-- End Horizontal Form -->

                    </div>
                </div>
                
            </div>
        </div>
     </section>
</main>

@section Scripts {
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.3/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.12/jquery.validate.unobtrusive.min.js"></script>

}

Quiz_Application/Quiz_Application/Views/MST_Question/QuestionList.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model DataTable
@using System.Data
<main id="main" class="main">

    <div class="pagetitle">
        <h1>Question List </h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a asp-Controller="Home" asp-action="Index">Home</a></li>
                <li class="breadcrumb-item">Tables</li>
                <li class="breadcrumb-item active">Data</li>
            </ol>
        </nav>
    </div><!-- End Page Title -->
    <section class="section">
        <div class="row">
            <div class="col-lg-12">

                <div class="card">
                    <div class="card-body">
                        <div>
                            <h5 class="card-title">Search Question</h5>

                          <form class="row g-3" asp-controller="MST_Question" asp-action="QuestionSearch" method="get">
                           @{
                            var selectedLevel = ViewBag.QuestionLevel?.ToString();
                            }
                        <div class="col-md-4">

                            <label for="questionLevel" class="form-label">Question Level</label>
                            <select name="questionLevel" class="form-control">
                                <option value="">Select Level</option>
                                @if(ViewBag.QuestionLevels != null){
                                    foreach(var v in ViewBag.QuestionLevels){
                                        <option value="@v.QuestionLevelID">@v.QuestionLevelName</option>
                                    }            
                                }
                            </select>
                        </div>

                                    <div class="col-md-4">
                                        <label for="questionText" class="form-label">Question</label>
                                        <input type="text" name="questionText" value="@ViewBag.QuestionText" class="form-control border border-black" placeholder="Enter Question">
                                    </div>
                                   <div class="col-md-4">
                                        <label for="questionMarks" class="form-label">Question Marks</label>
                                        <input type="number" name="questionMarks" value="@ViewBag.QuestionMarks" class="form-control border border-black" placeholder="Enter Question Marks">
                                    </div>

                                    <div class="text-start">
                                        <button type="submit" class="btn btn-success">Search</button>
                                        <button type="reset" onclick="window.location.href='@Url.Action("QuestionList","MST_Question")'" class="btn btn-danger">Reset</button>
                                    </div>
                            </form>
                        </div>

                        </div>

                        </div>
                        </div>
                        </div>
                        </section>

            <br />
                 <div class="text-danger">
                            @{
        if (@TempData["SuccessMessage"] != null)
        {
            <p>@TempData["SuccessMessage"]</P>
    }
     if (@TempData["ErrorMessage"] != null)
        {
            <p>@TempData["ErrorMessage"]</P>
    }
    }
    </div>

    <section class="section">
        <div class="row">
            <div class="col-lg-12">

                <div class="card">
                    <div class="card-body">
                       
                            

                      

                        <div class="overflow-x-scroll">
                        <!-- Table with stripped rows -->
                        <table class="table datatable" class="display nowrap " style="width:100%" >
                                <h2 class="p-3">Question List</h2>
                                 <div class="m-3">
                                <a asp-controller="MST_Question" asp-action="ExportToExcel" class="btn btn-primary float-end ms-2">
                                    <i class="fa fa-file-excel"></i> Download Excel
                                </a>
                            </div>
                                <div class="d-flex justify-content-end">
                                    <a asp-controller="MST_Question" asp-action="QuestionForm" class="btn btn-success w-20">
                                        <i class="bi bi-plus"></i> Add Question
                                    </a>
                                </div>
                            <thead>
                                <tr>
                                    <th>Question ID</th>
                                    <th>Question Text</th>
                                    <th>Question Level </th>
                                    <th>Option A</th>
                                    <th>Option B</th>
                                    <th>Option C</th>
                                    <th>Option D</th>
                                    <th>Correct Option</th>
                                    <th>Question Marks</th>
                                    <th> Active</th>
                                    <th>User Name</th>

                                    <th>Created</th>
                                    <th>Modified</th>
                                     <th>Action</th>

                                </tr>
                            </thead>
                            <tbody>
                                    @foreach (DataRow dataRow in Model.Rows)
                                    {
                                        <tr>
                                            <td>@dataRow["QuestionID"]</td>
                                            <td>@dataRow["QuestionText"]</td>
                                            <td>@dataRow["QuestionLevel"]</td>
                                            <td>@dataRow["OptionA"]</td>
                                            <td>@dataRow["OptionB"]</td>
                                            <td>@dataRow["OptionC"]</td>
                                            <td>@dataRow["OptionD"]</td>
                                            <td>@dataRow["CorrectOption"]</td>
                                            <td>@dataRow["QuestionMarks"]</td>

                                            <td>@dataRow["IsActive"]</td>
                                            <td>@dataRow["UserName"]</td>

                                            <td>@dataRow["Created"]</td>
                                            <td>@dataRow["Modified"]</td>
                                            <td>
                                                <a asp-controller="MST_Question" asp-action="QuestionForm"  asp-route-QuestionID="@dataRow["QuestionID"]"  class="btn btn-primary btn-sm" onclick="return confirm('Are you sure you want to Edit this Question?')">
                                                    <i class="bi bi-pencil-fill"></i>Edit

                                                </a>
                                                <a asp-controller="MST_Question" asp-action="QuestionDelete" asp-route-QuestionID="@dataRow["QuestionID"]" class="btn btn-danger btn-sm"  onclick="return confirm('Are you sure you want to delete this Question?')">
                                                    <i class="bi bi-trash">Delete</i>
                                                </a>

                                            </td>
                                        </tr>

                                    }
                            </tbody>
                               
                            </table>
                        <!-- End Table with stripped rows -->
                        </div>

                    </div>
                </div>

            </div>
        </div>
    </section>